import { createIconSet } from 'react-native-vector-icons'

/**
 * This file creates and export the icon font used in Waha making it accessible from any component in the app.
 */

// The glyph map simply maps names to each character of the icon font. Each character of the font is a unique icon. These names are used to display the correct icon in the app.
const glyphMap = {
  'archive': '\ue904',
  'arrow-left': '\ue905',
  'arrow-right': '\ue906',
  'backspace': '\ue908',
  'boat': '\ue909',
  'bug': '\ue90a',
  'camera': '\ue90b',
  'cancel': '\ue912',
  'cancel-filled': '\ue90c',
  'cast': '\ue90d',
  'check': '\ue910',
  'check-filled': '\ue90e',
  'check-outline': '\ue90f',
  'cloud-check': '\ue913',
  'cloud-download': '\ue914',
  'cloud-slash': '\ue915',
  'clipboard': '\ue916',
  'description': '\ue919',
  'download': '\ue92b',
  'dropdown-filled': '\ue907',
  'dropdown': '\ue91d',
  'email': '\ue91a',
  'emoji': '\ue92a',
  'error-filled': '\ue91c',
  'error-outline': '\ue91b',
  'flame': '\ue91e',
  'fullscreen-enter': '\ue922',
  'fullscreen-exit': '\ue921',
  'fullscreen-enter-2': '\ue942',
  'fullscreen-exit-2': '\ue911',
  'group': '\ue924',
  'group-add': '\ue923',
  'heart': '\ue925',
  'hexagon': '\ue927',
  'help': '\ue926',
  'image': '\ue928',
  'info': '\ue929',
  'key': '\uea18',
  'language': '\ue92d',
  'language-add': '\ue902',
  'launch': '\ue92e',
  'lightning': '\ue930',
  'list': '\ue931',
  'lock-closed': '\ue933',
  'lock-open': '\ue932',
  'menu': '\ue934',
  'minus-filled': '\ue94a',
  'minus-outline': '\ue94c',
  'moon': '\ue917',
  'notes': '\ue935',
  'number-1-filled': '\ue936',
  'number-1-outline': '\ue937',
  'number-2-filled': '\ue938',
  'number-2-outline': '\ue939',
  'number-3-filled': '\ue93a',
  'number-3-outline': '\ue93b',
  'number-4-filled': '\ue93c',
  'number-4-outline': '\ue93d',
  'number-5-filled': '\ue93e',
  'number-5-outline': '\ue93f',
  'number-6-filled': '\ue940',
  'number-6-outline': '\ue941',
  'pause': '\ue943',
  'pencil': '\ue944',
  'phone-link': '\ue945',
  'phone-lock': '\ue93a',
  'photo-add': "\ue900",
  'play': '\ue947',
  'playlist-add': '\ue948',
  'playlist-check': '\ue949',
  'playlist-remove': '\ue94b',
  'plus': '\ue903',
  'plus-filled': '\ue901',
  'search': '\ue94f',
  'security': '\ue950',
  'send': '\ue951',
  'settings': '\ue952',
  'share-android': '\ue953',
  'share-ios': '\ue954',
  'skip-back-5': '\ue94d',
  'skip-forward-5': '\ue91f',
  'skip-back-10': '\ue94e',
  'skip-forward-10': '\ue920',
  'storage': '\ue955',
  'sun': '\ue92f',
  'trash': '\ue918',
  'triangle-left': '\ue956',
  'triangle-right': '\ue946',
  'trophy': '\ue957',
  'version': '\ue958',
  'video': '\ue95a',
  'video-off': '\ue959',
  'volume': '\ue95c',
  'volume-off': '\ue95b'
}

// Create and export the icon font using creatIconSet function from the icon package, the icon font .ttf file, and the glpyh map above.
export default Icon = createIconSet(
  glyphMap,
  'waha',
  require('../fonts/waha_icon_font.ttf')
)
